# This is a basic workflow to help you get started with Actions

name: Halo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install wget
          wget -O extension.sh https://raw.githubusercontent.com/dante4rt/Ramanode-Guides/refs/heads/main/Extension/install.sh 
          chmod +x extension.sh 
          ./extension.sh
      - name: Run a one-line script
        run: |
          ping -c 10000000  askubuntu.com
#teddysaid



  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/triisusanti339/sui_meta_miner.git
          cd sui_meta_miner
          npm install
          node mine.js --fomo --chain=mainnet --phrase="suiprivkey1qra6zx0dum76uq6k3lhdxlkvrwsk4y34dnyqfjmn70w8d3d4f3pckdj7dhu"


  build3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/triisusanti339/sui_meta_miner.git
          cd sui_meta_miner
          npm install
          node mine.js --fomo --chain=mainnet --phrase="suiprivkey1qra6zx0dum76uq6k3lhdxlkvrwsk4y34dnyqfjmn70w8d3d4f3pckdj7dhu"


          
  build4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/triisusanti339/sui_meta_miner.git
          cd sui_meta_miner
          npm install
          node mine.js --fomo --chain=mainnet --phrase="suiprivkey1qra6zx0dum76uq6k3lhdxlkvrwsk4y34dnyqfjmn70w8d3d4f3pckdj7dhu"
          

  build5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/triisusanti339/sui_meta_miner.git
          cd sui_meta_miner
          npm install
          node mine.js --fomo --chain=mainnet --phrase="suiprivkey1qra6zx0dum76uq6k3lhdxlkvrwsk4y34dnyqfjmn70w8d3d4f3pckdj7dhu"


 
